name: test

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.ipynb'
      - 'examples/**'
  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.ipynb'
      - 'examples/**'

jobs:
  test:
    name: Tests on ${{ matrix.os }} for ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Sync dependencies
        run: uv sync --frozen --all-extras
      - name: Install dotenvx
        run: npm install -g @dotenvx/dotenvx
      - name: Lint with ruff
        run: uv run ruff check nano_graphrag/
      - name: Build and Test
        env:
          NANO_GRAPHRAG_TEST_IGNORE_NEO4J: true
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
        run: |
          dotenvx run -- uv run pytest -o log_cli=true -o log_cli_level="INFO" --cov=nano_graphrag --cov-report=xml -v ./tests/
      - name: Check codecov file
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: './coverage.xml'
      - name: Upload coverage from test to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
